/*------------------------------ WATERMARK FUNCTION ON SERCH ONCLICK--------------------------- */
function watermarkreport(){	
	var army_no = localStorage.getItem("army_no");
	
	Array.from(document.querySelectorAll('.watermarked')).forEach(function (el) {
		var wtmarklbl=" Generated by "+username;
		if(army_no != "" & army_no != null){
			wtmarklbl +=" ["+army_no+"]";
		}
		wtmarklbl += " on "+ curDate;	
		
		el.dataset.watermark = (wtmarklbl + ' ').repeat(20000);
	});	
}
function nrSetWaterMark(pline){
	var ab="";
	abip="Generated by " + username +" ["+army_no+"] on "+curDate;
	for (var i = 0; i <pline*2; i++) {
		ab=ab+abip+" ";
	}
	$(".nrWatermarkBase p").text(ab);
}